[phases.setup]
run = "pip install -r requirements.txt"

[phases.build]
run = "python manage.py collectstatic --noinput && python manage.py migrate"

[phases.start]
run = "gunicorn home_decor_backend.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --log-file -"

RUN apt-get update && \
    apt-get install -y python3-venv && \
    python -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim
