[phases.setup]
run = "pip install -r requirements.txt"

[phases.build]
run = "python manage.py collectstatic --noinput && python manage.py migrate"

[phases.start]
run = "gunicorn home_decor_backend.wsgi:application --bind 0.0.0.0:$PORT --timeout 120"
